version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:latest
    container_name: notification_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret_password
      MONGO_INITDB_DATABASE: notification_db
    volumes:
      - mongo_data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 756 > /data/db/keyfile
        chmod 400 /data/db/keyfile
        chown 999:999 /data/db/keyfile
        exec docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/db/keyfile --bind_ip_all
    # Healthcheck container
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "secret_password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: notification_app
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file:
      - .env

volumes:
  mongo_data: